# -*- coding: utf-8 -*-
"""Ejercicio6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktaoeEFQNo2GkiIyDcJdZhaNfYcA_I2_
"""

# EJERCICIO 6
import matplotlib.pyplot as plt
import networkx as nx

# Crear un grafo dirigido
G = nx.DiGraph()

# Definir personas
personas = [
    abuelo_pat, abuela_pat, abuelo_mat, abuela_mat,
    padre, madre, hijo1, hijo2, hijo3, hijo4, hijo5
]

# Agregar nodos al grafo
for persona in personas:
    G.add_node(persona.nombre, genero=persona.genero)

# Agregar relaciones al grafo
for persona in personas:
    for padre in persona.padres:
        G.add_edge(padre.nombre, persona.nombre)

# Definir posición de los nodos
pos = nx.spring_layout(G)

# Obtener etiquetas de género
genero_labels = nx.get_node_attributes(G, 'genero')

# Dibujar el grafo
nx.draw(G, pos, with_labels=True, labels={node: node for node in G.nodes()}, node_size=1500, node_color='lightblue', font_size=10, font_weight='bold', arrows=True)

# Mostrar el gráfico
plt.title("Árbol Genealógico")
plt.show()