# -*- coding: utf-8 -*-
"""Ejercicio10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktaoeEFQNo2GkiIyDcJdZhaNfYcA_I2_
"""

print ("hola mundo")